### PR TITLE
fix #160

### LINKED ISSUE #160: installation of master fails for missing checkbashisms
```
devtools::install_github(repo="knausb/vcfR")
Downloading GitHub repo knausb/vcfR@master
✓  checking for file ‘/tmp/RtmpqOTXiK/remotes1c102254e545/knausb-vcfR-6c2b1d3/DESCRIPTION’ (926ms)
─  preparing ‘vcfR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘vcfR_1.11.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/rsession-store/gleixner/R/4.0.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘vcfR’ ...
** using staged installation
./configure: line 4: checkbashisms: command not found
Error in system(cmd) : (converted from warning) error in running command
* removing ‘/rsession-store/gleixner/R/4.0.0/vcfR’
 Error: Failed to install 'vcfR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpqOTXiK/file1c102c445fc0/vcfR_1.11.0.tar.gz’ had non-zero exit status 
```
This is on `R 4.0.0` on  `CentOS Linux 7`.  The dev  branch (still) works.
Should this configure script be here at all, or was it perhaps committed by accident?

### PR DESCRIPTION
**Pull request by jan-glx**
This fixes #160.

### CODE REVIEW

**Comment by jan-glx** [comment]
Appveyor ran through too now (thanks to 9fb4557 allowing source dependencies), remaining CI errors are unrelated warnings from a bad link in the documentation:
```
* checking Rd cross-references ... WARNING
Non-file package-anchored link(s) in documentation object 'chromR-class.Rd':
  '[base]{tolower}'

See section 'Cross-references' in the 'Writing R Extensions' manual.
```

**Comment by knausb** [comment]
The suggestion to remove ```configure``` was raised and addressed in other issues. Modification of the appveyor yaml should only affect appveyor, so I don't see why it's necessary. Appveyor failed for your PR but I'm guessing it has to do with dependencies still being sorted out from the major release of R 4.0.0.

Thank you @jan-glx for proposing a solution!
Brian

**Comment by jan-glx** [comment]
Great to hear that you fixed #160 yourself now (with b59851027 and 55aed8f8d18f7d867f7)! 🎉 
 I included  9fb4557 in this PR such that appvoyer will also consider source packages when installing dependencies and thus be able to check my changes. 
You might want to consider merging / cherry picking 9fb4557 nevertheless to enable CI for windows again (in my experience there are always some packages that require compilation on windows). (Or do you really want to check that windows users don't need build tools to use vcfr?)

**Comment by knausb** [comment]
Hi @jan-glx ,

It appears that I did not understand what ``` PKGTYPE: both``` did. And now I do. It appears we've gone full circle in that I did not accept your PR but have now incorporated all of your proposals. We seem to have landed at "you understood this better than I did from the beginning." Apologies, you're working with a human here. Thank you for proposing solutions! And thank you for being persistent!

Brian

**Comment by jan-glx** [comment]
Very human response. Much appreciated!

**Pull request closed without merging**
