### PR TITLE
Add tidy stuff

### PR DESCRIPTION
**Pull request by eriqande**
Hey Brian,

I just submitted my referee report for your paper about vcfR.  Outstanding work!  It's a beautiful R package and I learned a lot about how to cleanly put together a package by looking it over.  I think it will be very useful.  As I indicated in my review, the one thing that seemed missing from the package was a quick way to convert vcfR objects to tidy data frames for use with dplyr, tidyr, and ggplot2.  I think that functionality will be very useful to a lot of users, so I added it in a file `R/vcfR_to_tidy_functions.R` that includes about four or five functions.  They are all documented together on a single documentation page.  I also imported the pipe operator `%>%` from `magrittr` and added a couple of Hadley's packages to the Imports that were needed/useful within those functions.  

Anyway, I hope that this is useful enough to add to your package, and I look forward to seeing your manuscript in print.  

I am fine with this being put under any open source license.  

Congrats again on vcfR.

eric

### CODE REVIEW

**Comment by eriqande** [comment]
Your travis-ci build caught a bunch of stuff that I would have caught if I had run R CMD CHECK.  I think I have fixed most of that now.  The big culprit was non-standard evaluation.  That appears to be fixed now.

**Comment by knausb** [comment]
Hi Eric,

My first thoughts when I saw your pull request and comments was 'wow, world's best review!' And then I hesitated. The reason I hesitated was because I was concerned that including a reviewer as a contributor could be interpreted as a conflict of interest, depending on who's doing the interpreting. We don't ask our co-authors to review our papers and if someone didn't take the time to scrutinize dates it could appear that a contributor has reviewed the manuscript. I've asked the opinions of some colleagues and we've agreed that this does not present a problem. One thought though was that if you had not revealed yourself as a reviewer I would not have known to hesitate. Perhaps something to consider in the future? Or perhaps I just like to over think things sometimes. Anyhow, I thought I'd share my thoughts.

Thank you very much for your contribution! I think this will make a great addition. Could you please add your name to the DESCRIPTION as a contributor (role = ctb). And then I'll have to learn a bit about merging pull requests.

Thanks!

**Comment by eriqande** [comment]
Hi Brian,

Cheers.  I've added myself in as a 'ctb'.

Yes, I had wondered if there might be some weird-looking conflict of interest there.  But I was just so eager to contribute.  I agree that it shouldn't be a problem, though---a lot referee comments end up making their way into finished products (and I am pretty sure the AE is Thierry Gosselin who will know the backstory on all this).  The only thing that would make me feel funny would be if you guys felt (in any way) like I was using my role as a referee to strong-arm you into making me a contributor on the project.  I definitely wouldn't want you to feel that way at all.  I'll admit that, having added myself as a "ctb" to the author line, the package DESCRIPTION looks weird with my name anywhere near your two names!---you two have two years worth of commits on the project and I just spent a couple of days adding a few functions.  So, if it would be more comfortable, I would gladly bequeath the code I wrote to you without attribution.  

Good luck with the merging of the pull request, etc.  I am not super well versed in that, either.  This seems to be a [good intro](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project).  I think you'll want to checkout a new branch off of master (or devel), then fetch my stuff and merge it into the new branch and test it.  Then if it all looks good, merge it into master or devel.

Is that picture of you on your GitHub page from the MacDonald forest near OSU?  I came up for a long weekend one September and did a lot of nighttime mountain biking up there.  Cool spot!

Best regards,

eric

**Comment by zkamvar** [comment]
Sorry to butt in, but I wanted to throw my two cents in here, having worked on a couple of collaborative packages myself :smile: 

>  I'll admit that, having added myself as a "ctb" to the author line, the package DESCRIPTION looks weird with my name anywhere near your two names!---you two have two years worth of commits on the project and I just spent a couple of days adding a few functions.

IMO, it's ultimately up to the maintainer to determine what contributions are worthy of being added to the list of contributors. For example, David Winter's philosophy is that [ANY contribution is worthy of the "ctb" role](https://github.com/dwinter/mmod/commit/1c542b9f51d7d7ff2c744723fba0e79842fd8907#commitcomment-11902717). Additionally, Hadley Wickham's book on R packages lists criteria for these roles: http://r-pkgs.had.co.nz/description.html#author; given that definition, I would definitely say that @eriqande deserves the ctb role. :+1:

Additionally, merging the pull request is as easy as clicking the green button below :smiley:

**Comment by eriqande** [comment]
Cool!
Let me know if there are any issues/glitches that need resolving.  

thanks for your comments zkamvar!  It's nice that R has the "ctb" role.  This whole open community thing is super cool.  You guys have a lot of cool stuff going on in your lab too.  Cheers.

**Comment by knausb** [comment]
HI Eric,

I definitely see this as a contribution. I've been slow to embrace the Hadleyverse perspective on R. So I admittedly don't understand much of your code. But it definitely has the look of polished code! If it only took you a couple of days its because you're good! Part of the reason it took us two years is I had to learn things (Rcpp, C++, roxygen2, S4, etc.). And besides, including you as a contributor not only gives you the credit you deserve, it provides your contact in case anyone has questions about your code. So it serves a practical role as well. You've definitely earned a place as a contributor. Thanks for helping to make vcfR better!

Merging turned out to be pretty simple. When I cloned your version to my local box it took me longer than I want to admit to figure out that a branch had been created for your changes. So I think you're correct that merging it would have handled it. But as Zhian pointed out, merging on GitHub was as simple as pushing a button (well, and a confirmation button). The Travis-ci is really nice for screening stuff, as you found out, so I don't really think I need to worry about testing your code, although I did try it on my local machine to see how it works.

As you know, the manuscript is currently in review. So my plan is to keep the CRAN version stable until I get all the comments back and have had an attempt to address them. At which point I should release another version to CRAN. At that point you should see your additions. Until then, you can use the master branch if you'd like.

Yup, that's the Mac! We're super fortunate to have that in our backyard. You'll find me out there trail running most weekends.

Thanks!

**Comment by knausb** [comment]
And @zkamvar, your butt ins are always welcome! You've got some really good perspectives that I value. Sorry if I tend to be stubborn. I do listen sometimes :)

**Comment by eriqande** [comment]
Great!  I pulled that down into my fork too and it all looks good.  Super fun stuff.  Impressive learning of all that in the last two years Brian!  I hope the other reviews of helpful and good on the paper too. Best regards.

**Pull request merged**
