### PR TITLE
Tiny fix to parse INFO fields with "=" in their values.

### PR DESCRIPTION
**Pull request by eriqande**
I think this is a little safer and more robust all the way around too.

### CODE REVIEW

**Comment by eriqande** [comment]
Hey Brian!

I hope all is well with you.  I got an email from someone who had INFO fields from VEP that included equals-signs in their values.  That violates the 4.1 VCF standard, and also screwed up vcfR2tidy(). 

As it turns out, a simple fix let's us split key=value pairs on just the first equals sign.  This is a better way to do it anyway, as it should also give better results when there is no equals sign.  

`vcfR_to_tidy_functions.R` is the only file with real changes in it.  The rest were changes that occurred when I compiled it and I needed to put them up there so she could devtools::install_github the new version from my fork.

eric

**Comment by knausb** [comment]
Hi Eric, great to hear from you! And thanks for going through the effort to make a PR! Your PR seems to pass fine and I think I understand the situation. But I'd like to talk about it a bit as a way of documenting this in case someone else reads this at some point.

The VCF specification is currently at v4.3. In section 1.6.2 'Fixed fields' part 8 - INFO indicates that equals-signs are not permitted. This appears to be due to the key-value pairs being delimited by an equals-sign. This means that this PR is not to support a valid VCF file but to add friendlier handling of data that does not strictly follow the specification. I'm fine with this and have done it elsewhere in vcfR. But I just wanted to make clear that this is non-standard.

I have not encountered this sort of data. And I'm trying to incorporate more unit tests in vcfR. So I'm hoping you can help me construct a minimal reproducible example. We can load a small dataset as follows.

```
library(vcfR)
data("vcfR_test")
```

We can access and modify the first INFO value as follows.

```
vcfR_test@fix[1,'INFO'] <- "NS=3;DP=14;AF=0.5;DB;H2"
```

Here I've replaced it with its existing value. My hope is that you can modify this so it appears similar to the INFO values reported by your colleague. We should now be able to process the data.

```
vcfR2tidy(vcfR_test, info_only = TRUE)$fix
```

If you could modify this example so that it appears as the data your colleague has shared with you I can make it into a unit test to make sure this stays fixed in the future.

We just updated vcfR on CRAN last month. But we're currently hoping to get another update in February. That update will include your PR. Thanks!

Brian

**Comment by eriqande** [comment]
Hi Brian, 

Thanks for you reply.  Yes, that is correct.  Their file violates the standard, but is apparently created by some standard software, and it doesn't break vcfR to be able to read in these fields that have extra equals signs.

Here is a minimal example that the user sent to me.  The problem is that they are reporting test result P-values using a string like "P_=_0.006"  within the CSG field. 

```
##fileformat=VCFv4.1
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|ENSP|SOURCE|GENE_PHENO|NEAREST|SIFT|PolyPhen|DOMAINS|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|CELL_TYPE|ExACpLI|LoFtool|MaxEntScan_alt|MaxEntScan_diff|MaxEntScan_ref|SpliceRegion|GeneSplicer|GWAVA|GWAVA|LoF|LoF_filter|LoF_flags|LoF_info|FDR|MTR|MTR_centile|MPC|FATHMM_MKL_C|FATHMM_MKL_NC|CADD_PHRED|CADD_RAW|LRT_Omega|LRT_converted_rankscore|LRT_pred|LRT_score|M-CAP_pred|M-CAP_rankscore|M-CAP_score|MetaLR_pred|MetaLR_rankscore|MetaLR_score|MetaSVM_pred|MetaSVM_rankscore|MetaSVM_score|MutPred_AAchange|MutPred_Top5features|MutPred_protID|MutPred_rankscore|MutPred_score|MutationAssessor_pred|MutationAssessor_rankscore|MutationAssessor_score|MutationTaster_converted_rankscore|MutationTaster_pred|MutationTaster_score|PROVEAN_converted_rankscore|PROVEAN_pred|PROVEAN_score|REVEL_rankscore|REVEL_score|Reliability_index|SiPhy_29way_logOdds|SiPhy_29way_logOdds_rankscore|SiPhy_29way_pi|VEST3_rankscore|VEST3_score|ada_score|rf_score|LinkedVariants|gnomADg|gnomADg_AF_AFR|gnomADg_AF_AMR|gnomADg_AF_ASJ|gnomADg_AF_EAS|gnomADg_AF_FIN|gnomADg_AF_NFE|gnomADg_AF_OTH|GERP|phastCons100|phyloP100">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
1	1459319	CM174964	G	A	.	.	CSQ=A|missense_variant|MODERATE|ATAD3A|ENSG00000197785|Transcript|ENST00000378755|protein_coding|10/16||||1302/2612|1208/1905|403/634|G/D|gGc/gAc|||1||SNV|HGNC|25567|YES|ENSP00000368030||1|ATAD3A|deleterious(0)|probably_damaging(1)|hmmpanther:PTHR23075&hmmpanther:PTHR23075:SF4&Pfam_domain:PF00004&Gene3D:3.40.50.300&SMART_domains:SM00382&Superfamily_domains:SSF52540||||||||||||||||||||||||||||0.04|0.095|||||||||||DE_NOVO_DONOR_MES_POS:-26&EXON_START:1459219&DE_NOVO_DONOR_POS:-26&DE_NOVO_DONOR_PROB:0.0457686823054549&INTRON_START:1459345&INTRON_END:1459652&EXON_END:1459344&MUTANT_DONOR_MES:8.68006700219329&DE_NOVO_DONOR_MES:-5.88477916315195|0.393|0.827|27.705|4.21975213468|0.97118|0.99031|24.9|4.860247|0.055989|0.64402|D|0.000001|D|0.97415|0.67075902506|D|0.99635|0.9866|D|0.96993|0.9723|G403D|Loss_of_MoRF_binding_(P_=_0.0725)&_Loss_of_catalytic_residue_at_G403_(P_=_0.0852)&_Gain_of_relative_solvent_accessibility_(P_=_0.09)&_Loss_of_glycosylation_at_P402_(P_=_0.09)&_Gain_of_phosphorylation_at_Y399_(P_=_0.102)|Q9NVI7|0.95986|0.863|H|0.99649|4.795|0.80722|D&D&D|1&1&1|0.93144|D&D&D&D|-6.76&-6.91&-6.65&-6.88|0.96988|0.886|10|16.6957|0.85335|0.0:0.0:1.0:0.0|0.87411|0.885||||||||||||4.69999980926514|1|7.54699993133545

```
This should be enough to create a minimal example vcf to your liking for unit tests.

Thanks for being so diligent in maintaining vcfR.  It looks like it is getting a lot of use.

Best wishes,

eric

**Comment by knausb** [comment]
That's fantastic Eric! Thank you so much! One of the interesting parts of this project is people informing me of all the tools out there that create and work with VCF data. The downside is that if they ask me for help or a feature from I software I have no experience with I'm frequently at a loss. So its really nice to have some data that illustrates this.

I've merged your changes to master and your example can be accessed as follows.

```
data(vep)
```

I still need to work on the unit tests, but all the pieces appear in place. Again, I think you'll see this on CRAN in February.

Thank you for your help!
Brian

**Pull request merged**
